replicaCount: 1

image:
  repository:
  tag:
  pullPolicy: Always

service:
  type: ClusterIP
  ports: []

container:
  ports: []

ingressroute:
  enabled: false
  match: Host(`generic.xxx.xxx`) && PathPrefix(`/generic`)

persistence:
  enabled: true
  storageClass: nfs-client
  size: 1Gi
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
