version: "3"
services:

  zookeeper:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
    volumes:
      - ./data/zk:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:2.8.0
    container_name: kafka
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    restart: unless-stopped
    volumes:
      - ./data/kfk:/bitnami/kafka

  top-tweets-stream-collector:
    image: ljufa/top-tweets-stream-collector:latest
    container_name: top-tweets-stream-collector
    env_file:
      - .env
    depends_on:
      - kafka
    restart: unless-stopped

  top-tweets-backend:
    image: ljufa/top-tweets-backend:latest
    container_name: top-tweets-backend
    ports:
      - '1977:1977'
    depends_on:
      - kafka
    restart: unless-stopped

  top-tweets-web:
    image: ljufa/top-tweets-web:latest
    container_name: top-tweets-web
    ports:
      - '8080:8080'
    depends_on:
      - top-tweets-backend
    restart: unless-stopped
