api:
  dashboard: false
  debug: true

log:
  level: "DEBUG"

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

providers:
#  file:
#    watch: false
#    filename: ./routes.yaml
#    debugLogGeneratedTemplate: true

  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedbydefault: false
