apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "generic.fullname" . }}
  labels:
    app: {{ template "generic.name" . }}
    chart: {{ template "generic.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key,$val:= .Values.configmap}}
  {{- if $val}}
  {{$key}}: {{printf "%v" $val | trimSuffix "\"" | trimSuffix "\\" | trimPrefix "\\" | trimPrefix "\"" | quote}}
  {{- else}}
  {{$key}}: ""
  {{- end}}
{{- end}}